### ISSUE TITLE
Create a SchoolController.getStudentById

### ISSUE THREAD

**Issue by LorenzoBettini** [LorenzoBettini/example.exercise#16]
Create a class SchoolController that uses a Database with method

Student getStudentById()

that searches in the database for a student with a given id and returns the Student object or null if no Student can be found.

**Comment by ma-buracchi** [comment]
I believe there is a typo in the method signature.
It has to be Student getStudentyById() or Student getStudentById()?
Waiting for your response I'll start working on getStudentyById().

**Comment by LorenzoBettini** [comment]
right, there was a typo, the correct form is getStudentById

**Comment by LorenzoBettini** [comment]
Closed by https://github.com/LorenzoBettini/example.exercise/pull/29
